<template>
  <div class="space-y-5">
    <div class="flex gap-2 overflow-x-auto rounded-xl border border-border bg-card p-2"><button v-for="tab in tabs" :key="tab.value" class="whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold" :class="activeTab === tab.value ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'" @click="activeTab = tab.value">{{ tab.label }}</button></div>
    <BaseCard v-if="activeTab === 'advancement'">
      <div class="mb-4 flex items-center justify-between"><div><h3 class="font-semibold">Tạm ứng phép</h3><p class="text-xs text-muted-foreground">Nhân viên gửi → Trưởng phòng duyệt → HR duyệt và ghi sổ phép.</p></div><BaseButton @click="openCreate">+ Xin tạm ứng</BaseButton></div>
      <div v-if="loading" class="py-8 text-center text-muted-foreground">Đang tải...</div>
      <div v-else class="overflow-x-auto rounded-xl border border-border"><table class="w-full min-w-[850px] text-sm"><thead class="bg-muted/40 text-left text-xs uppercase text-muted-foreground"><tr><th class="px-3 py-2.5">Nhân viên</th><th class="px-3 py-2.5">Loại phép</th><th class="px-3 py-2.5">Số ngày</th><th class="px-3 py-2.5">Lý do</th><th class="px-3 py-2.5">Trạng thái</th><th class="px-3 py-2.5"></th></tr></thead><tbody>
        <tr v-for="item in requests" :key="item.id" class="border-t border-border/70"><td class="px-3 py-3">{{ item.employee_name || 'Tôi' }}</td><td class="px-3 py-3">{{ item.leave_type_name }}</td><td class="px-3 py-3 font-semibold">{{ item.advance_days }}</td><td class="max-w-sm px-3 py-3">{{ item.reason }}</td><td class="px-3 py-3">{{ statusLabel(item.status) }}</td><td class="px-3 py-3 text-right whitespace-nowrap"><button v-if="canManager && item.status === 'PENDING_MANAGER'" class="text-xs font-semibold text-primary" @click="decide(item, 'manager')">Duyệt cấp phòng</button><button v-if="canHr && item.status === 'PENDING_HR'" class="ml-3 text-xs font-semibold text-primary" @click="decide(item, 'hr')">HR duyệt</button><button v-if="isMine(item) && ['PENDING_MANAGER','PENDING_HR'].includes(item.status)" class="ml-3 text-xs font-semibold text-destructive" @click="cancel(item)">Hủy</button></td></tr><tr v-if="!requests.length"><td colspan="6" class="py-8 text-center text-muted-foreground">Chưa có yêu cầu tạm ứng phép.</td></tr>
      </tbody></table></div>
    </BaseCard>
    <ResourceCrudPanel v-else-if="activeTab === 'config'" resource="leave-advancement-config" title="Cấu hình tạm ứng phép" :columns="configColumns" :fields="configFields" :defaults="{ status: 'ACTIVE' }" />
    <ResourceCrudPanel v-else-if="activeTab === 'ledger'" resource="leave-transactions" title="Sổ giao dịch phép" :columns="ledgerColumns" :fields="[]" read-only />
    <ResourceCrudPanel v-else-if="activeTab === 'carryover'" resource="leave-carryover-tracking" title="Theo dõi phép chuyển năm" :columns="carryoverColumns" :fields="[]" read-only />
    <ResourceCrudPanel v-else resource="seniority-leave-history" title="Lịch sử phép thâm niên" :columns="seniorityColumns" :fields="[]" read-only />

    <BaseModal v-model="createModal" title="Xin tạm ứng phép"><div class="space-y-4"><label class="block text-sm font-medium">Loại phép<ResourceSelect v-model="form.leave_type_id" resource="leave-types" label-key="leave_type_name" code-key="leave_type_code" /></label><label class="block text-sm font-medium">Số ngày<input v-model="form.advance_days" type="number" min="0.5" step="0.5" class="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2 font-normal" /></label><label class="block text-sm font-medium">Lý do<textarea v-model="form.reason" rows="4" class="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2 font-normal"></textarea></label><p v-if="formError" class="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{{ formError }}</p></div><template #footer><BaseButton variant="outline" @click="createModal = false">Hủy</BaseButton><BaseButton @click="create">Gửi yêu cầu</BaseButton></template></BaseModal>
    <BaseModal v-model="decisionModal" :title="decisionStage === 'manager' ? 'Trưởng phòng xử lý' : 'HR xử lý'"><div class="space-y-4"><p class="text-sm">{{ selected?.employee_name }} xin tạm ứng <strong>{{ selected?.advance_days }} ngày</strong>.</p><textarea v-model="decisionNote" rows="4" class="w-full rounded-lg border border-input bg-background px-3 py-2 text-sm" placeholder="Ghi chú; bắt buộc nếu từ chối"></textarea></div><template #footer><BaseButton variant="outline" @click="submitDecision('REJECT')">Từ chối</BaseButton><BaseButton @click="submitDecision('APPROVE')">Duyệt</BaseButton></template></BaseModal>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import BaseButton from './BaseButton.vue'; import BaseCard from './BaseCard.vue'; import BaseModal from './BaseModal.vue'; import ResourceCrudPanel from './ResourceCrudPanel.vue'; import ResourceSelect from './ResourceSelect.vue';
import { authService } from '../services/authService'; import { leaveAdvancementService } from '../services/leaveAdvancementService'; import { useToast } from '../composables/useToast';
const toast = useToast(); const actorId = computed(() => authService.getUser()?.employee_id); const canManager = computed(() => authService.hasCapability('leave.advance.manager')); const canHr = computed(() => authService.hasCapability('leave.advance.hr')); const canManage = computed(() => authService.hasCapability('leave.manage'));
const tabs = computed(() => [{ value: 'advancement', label: 'Tạm ứng phép' }, ...(canManage.value ? [{ value: 'config', label: 'Cấu hình' }] : []), { value: 'ledger', label: 'Sổ giao dịch' }, { value: 'carryover', label: 'Chuyển năm' }, { value: 'seniority', label: 'Thâm niên' }]); const activeTab = ref('advancement'); const loading = ref(false); const requests = ref([]); const createModal = ref(false); const decisionModal = ref(false); const selected = ref(null); const decisionStage = ref(''); const decisionNote = ref(''); const formError = ref(''); const form = reactive({ leave_type_id: '', advance_days: '1', reason: '' });
const statusLabel = (value) => ({ PENDING_MANAGER: 'Chờ Trưởng phòng', PENDING_HR: 'Chờ HR', APPROVED: 'Đã cộng phép', REJECTED_MANAGER: 'Trưởng phòng từ chối', REJECTED_HR: 'HR từ chối', CANCELLED: 'Đã hủy' }[value] || value); const isMine = (item) => String(item.employee_id) === String(actorId.value);
const load = async () => { loading.value = true; try { requests.value = (await leaveAdvancementService.list({ per_page: 100 })).items; } finally { loading.value = false; } }; const openCreate = () => { Object.assign(form, { leave_type_id: '', advance_days: '1', reason: '' }); formError.value = ''; createModal.value = true; };
const create = async () => { if (!form.leave_type_id || !form.reason.trim()) { formError.value = 'Chọn loại phép và nhập lý do'; return; } try { await leaveAdvancementService.create({ leave_type_id: Number(form.leave_type_id), advance_days: Number(form.advance_days), reason: form.reason }); createModal.value = false; await load(); } catch (error) { formError.value = error.response?.data?.message || Object.values(error.response?.data?.data?.errors || {}).flat().join(' ') || 'Không thể gửi yêu cầu'; } };
const decide = (item, stage) => { selected.value = item; decisionStage.value = stage; decisionNote.value = ''; decisionModal.value = true; }; const submitDecision = async (decision) => { if (decision === 'REJECT' && !decisionNote.value.trim()) { toast.error('Nhập lý do từ chối'); return; } const payload = { decision, note: decisionNote.value || null }; decisionStage.value === 'manager' ? await leaveAdvancementService.managerDecision(selected.value.id, payload) : await leaveAdvancementService.hrDecision(selected.value.id, payload); decisionModal.value = false; await load(); }; const cancel = async (item) => { if (!confirm('Hủy yêu cầu tạm ứng này?')) return; await leaveAdvancementService.cancel(item.id); await load(); };
const configColumns = [{ key: 'department_id', label: 'Phòng ban' }, { key: 'position_id', label: 'Chức danh' }, { key: 'max_advance_days', label: 'Tối đa (ngày)' }, { key: 'status', label: 'Trạng thái' }]; const configFields = [{ key: 'department_id', label: 'Phòng ban', type: 'resource', resource: 'departments', labelKey: 'department_name', codeKey: 'department_code', nullable: true, cast: 'number' }, { key: 'position_id', label: 'Chức danh', type: 'resource', resource: 'positions', labelKey: 'position_name', codeKey: 'position_code', nullable: true, cast: 'number' }, { key: 'max_advance_days', label: 'Tối đa ngày', type: 'number', min: 0.5, step: 0.5, cast: 'number', required: true }, { key: 'status', label: 'Trạng thái', type: 'select', options: [{ value: 'ACTIVE', label: 'Hoạt động' }, { value: 'INACTIVE', label: 'Ngừng' }] }];
const ledgerColumns = [{ key: 'employee_label', label: 'Nhân viên' }, { key: 'transaction_date', label: 'Ngày' }, { key: 'transaction_type', label: 'Loại' }, { key: 'quantity', label: 'Số ngày' }, { key: 'before_balance', label: 'Trước' }, { key: 'after_balance', label: 'Sau' }, { key: 'reason', label: 'Lý do' }]; const carryoverColumns = [{ key: 'employee_label', label: 'Nhân viên' }, { key: 'year', label: 'Năm' }, { key: 'carried_days', label: 'Chuyển sang' }, { key: 'used_days', label: 'Đã dùng' }, { key: 'expired_days', label: 'Hết hạn' }, { key: 'status', label: 'Trạng thái' }]; const seniorityColumns = [{ key: 'employee_label', label: 'Nhân viên' }, { key: 'calculation_date', label: 'Ngày tính' }, { key: 'years_of_service', label: 'Thâm niên' }, { key: 'base_leave', label: 'Phép cơ bản' }, { key: 'seniority_bonus', label: 'Cộng thêm' }, { key: 'total_leave', label: 'Tổng' }];
onMounted(load);
</script>
