<template>
  <div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><p class="text-xs font-bold uppercase tracking-[0.2em] text-cyan-600">Internal service desk</p><h1 class="mt-1 text-3xl font-bold">Hỗ trợ nội bộ</h1><p class="mt-1 text-muted-foreground">Mỗi ticket có danh mục chuẩn và timeline xử lý không thể xóa cứng.</p></div>
      <BaseButton v-if="activeTab === 'tickets'" @click="openCreate">+ Gửi yêu cầu</BaseButton>
    </div>

    <div v-if="canManage" class="flex gap-2 rounded-xl border border-border bg-card p-2">
      <button v-for="tab in tabs" :key="tab.value" class="rounded-lg px-3 py-2 text-sm font-semibold" :class="activeTab === tab.value ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'" @click="activeTab = tab.value">{{ tab.label }}</button>
    </div>

    <ResourceCrudPanel v-if="activeTab === 'categories'" resource="service-categories" title="Danh mục dịch vụ" description="Danh mục được dùng trực tiếp khi nhân viên tạo ticket." :columns="categoryColumns" :fields="categoryFields" :defaults="{ status: 'ACTIVE' }" />

    <template v-else>
      <div class="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <BaseCard v-for="item in summaryCards" :key="item.label"><p class="text-xs uppercase text-muted-foreground">{{ item.label }}</p><p class="mt-1 text-2xl font-black" :class="item.className">{{ item.value }}</p></BaseCard>
      </div>
      <BaseCard>
        <div class="mb-4 grid gap-3 sm:grid-cols-3">
          <input v-model="filters.search" class="rounded-lg border border-input bg-background px-3 py-2 text-sm" placeholder="Tìm mã hoặc tiêu đề" @keyup.enter="load" />
          <select v-model="filters.category_id" class="rounded-lg border border-input bg-background px-3 py-2 text-sm" @change="resetAndLoad"><option value="">Tất cả danh mục</option><option v-for="category in categories" :key="category.id" :value="String(category.id)">{{ category.category_name }}</option></select>
          <select v-model="filters.status" class="rounded-lg border border-input bg-background px-3 py-2 text-sm" @change="resetAndLoad"><option value="">Tất cả trạng thái</option><option v-for="status in statuses" :key="status.value" :value="status.value">{{ status.label }}</option></select>
        </div>
        <div v-if="loading" class="py-10 text-center text-muted-foreground">Đang tải...</div>
        <div v-else class="overflow-x-auto rounded-xl border border-border">
          <table class="w-full min-w-[850px] text-sm"><thead class="bg-muted/40 text-left text-xs uppercase text-muted-foreground"><tr><th class="px-3 py-2.5">Ticket</th><th class="px-3 py-2.5">Người gửi</th><th class="px-3 py-2.5">Danh mục</th><th class="px-3 py-2.5">Ưu tiên</th><th class="px-3 py-2.5">Trạng thái</th><th class="px-3 py-2.5"></th></tr></thead>
            <tbody><tr v-for="ticket in tickets" :key="ticket.id" class="border-t border-border/70"><td class="px-3 py-3"><p class="font-mono text-xs">{{ ticket.ticket_code }}</p><p class="font-semibold">{{ ticket.title }}</p></td><td class="px-3 py-3">{{ ticket.requester_name || 'Tôi' }}</td><td class="px-3 py-3">{{ ticket.category_name || 'Chưa phân loại' }}</td><td class="px-3 py-3">{{ priorityLabel(ticket.priority) }}</td><td class="px-3 py-3"><BaseBadge :variant="statusVariant(ticket.status)">{{ statusLabel(ticket.status) }}</BaseBadge></td><td class="px-3 py-3 text-right"><button class="text-xs font-semibold text-primary hover:underline" @click="openDetail(ticket)">Chi tiết</button><button v-if="canCancel(ticket)" class="ml-3 text-xs font-semibold text-destructive hover:underline" @click="cancelTicket(ticket)">Hủy</button></td></tr><tr v-if="!tickets.length"><td colspan="6" class="py-10 text-center text-muted-foreground">Chưa có ticket.</td></tr></tbody>
          </table>
        </div>
        <div v-if="pagination.last_page > 1" class="mt-4 flex items-center justify-between text-sm"><span class="text-muted-foreground">Trang {{ pagination.current_page }}/{{ pagination.last_page }} · {{ pagination.total }} ticket</span><div class="flex gap-2"><BaseButton variant="outline" :disabled="pagination.current_page <= 1" @click="goPage(-1)">Trước</BaseButton><BaseButton variant="outline" :disabled="pagination.current_page >= pagination.last_page" @click="goPage(1)">Sau</BaseButton></div></div>
      </BaseCard>
    </template>

    <BaseModal v-model="createModal" title="Gửi yêu cầu hỗ trợ">
      <div class="space-y-4"><label class="block text-sm font-medium">Danh mục<select v-model="form.category_id" class="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2 font-normal"><option value="">Chọn danh mục</option><option v-for="category in categories" :key="category.id" :value="String(category.id)">{{ category.category_name }}</option></select></label><BaseInput v-model="form.title" label="Tiêu đề" required /><label class="block text-sm font-medium">Ưu tiên<select v-model="form.priority" class="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2 font-normal"><option value="LOW">Thấp</option><option value="NORMAL">Bình thường</option><option value="HIGH">Cao</option><option value="URGENT">Khẩn cấp</option></select></label><label class="block text-sm font-medium">Mô tả<textarea v-model="form.description" rows="5" class="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2 font-normal"></textarea></label><p v-if="formError" class="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{{ formError }}</p></div>
      <template #footer><BaseButton variant="outline" @click="createModal = false">Hủy</BaseButton><BaseButton :disabled="saving" @click="createTicket">{{ saving ? 'Đang gửi...' : 'Gửi ticket' }}</BaseButton></template>
    </BaseModal>

    <BaseModal v-model="detailModal" title="Chi tiết ticket" size="lg">
      <div v-if="selected" class="space-y-5"><div class="rounded-xl bg-muted/40 p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-mono text-xs text-muted-foreground">{{ selected.ticket_code }}</p><h3 class="text-lg font-bold">{{ selected.title }}</h3><p class="text-xs text-muted-foreground">{{ selected.category_name }} · {{ selected.requester_name }}</p></div><BaseBadge :variant="statusVariant(selected.status)">{{ statusLabel(selected.status) }}</BaseBadge></div><p class="mt-4 whitespace-pre-line text-sm">{{ selected.description }}</p></div>
        <div v-if="canManage" class="grid gap-3 rounded-xl border border-border p-4 sm:grid-cols-3"><label class="text-xs font-semibold">Trạng thái<select v-model="manageForm.status" class="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm font-normal"><option v-for="status in statuses" :key="status.value" :value="status.value">{{ status.label }}</option></select></label><label class="text-xs font-semibold">Ưu tiên<select v-model="manageForm.priority" class="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm font-normal"><option v-for="priority in priorities" :key="priority.value" :value="priority.value">{{ priority.label }}</option></select></label><label class="text-xs font-semibold">Người/nhóm xử lý<input v-model="manageForm.assigned_to" class="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm font-normal" /></label><textarea v-model="manageForm.comment" rows="2" class="sm:col-span-3 rounded-lg border border-input bg-background px-3 py-2 text-sm" placeholder="Ghi chú cập nhật"></textarea><BaseButton class="sm:col-span-3" :disabled="saving" @click="updateTicket">Cập nhật xử lý</BaseButton></div>
        <div><h4 class="mb-3 font-semibold">Timeline</h4><div class="space-y-3"><div v-for="update in selected.updates || []" :key="update.id" class="border-l-2 border-primary/40 pl-4"><p class="text-sm font-medium">{{ update.created_by_name || 'Hệ thống' }} · {{ update.action_type }}</p><p class="text-xs text-muted-foreground">{{ dateTime(update.created_at) }}<span v-if="update.old_status !== update.new_status"> · {{ statusLabel(update.old_status) }} → {{ statusLabel(update.new_status) }}</span></p><p v-if="update.comment" class="mt-1 text-sm">{{ update.comment }}</p></div></div><div class="mt-4 flex gap-2"><input v-model="comment" class="flex-1 rounded-lg border border-input bg-background px-3 py-2 text-sm" placeholder="Thêm trao đổi" /><BaseButton variant="outline" :disabled="!comment.trim()" @click="addComment">Gửi</BaseButton></div></div>
      </div>
      <template #footer><BaseButton variant="outline" @click="detailModal = false">Đóng</BaseButton></template>
    </BaseModal>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import BaseBadge from '../components/BaseBadge.vue'; import BaseButton from '../components/BaseButton.vue'; import BaseCard from '../components/BaseCard.vue'; import BaseInput from '../components/BaseInput.vue'; import BaseModal from '../components/BaseModal.vue'; import ResourceCrudPanel from '../components/ResourceCrudPanel.vue';
import { authService } from '../services/authService'; import { serviceTicketService } from '../services/serviceTicketService'; import { useToast } from '../composables/useToast';
const toast = useToast(); const canManage = computed(() => authService.hasCapability('communications.manage')); const activeTab = ref('tickets'); const tabs = [{ value: 'tickets', label: 'Ticket' }, { value: 'categories', label: 'Danh mục dịch vụ' }];
const categories = ref([]); const tickets = ref([]); const loading = ref(false); const saving = ref(false); const createModal = ref(false); const detailModal = ref(false); const selected = ref(null); const comment = ref(''); const formError = ref(''); const filters = reactive({ search: '', category_id: '', status: '' }); const pagination = reactive({ current_page: 1, last_page: 1, total: 0 }); const summary = reactive({ total: 0, pending: 0, in_progress: 0, completed: 0 });
const form = reactive({ category_id: '', title: '', description: '', priority: 'NORMAL' }); const manageForm = reactive({ status: '', priority: '', assigned_to: '', comment: '' });
const statuses = [{ value: 'PENDING', label: 'Chờ xử lý' }, { value: 'IN_PROGRESS', label: 'Đang xử lý' }, { value: 'RESOLVED', label: 'Đã giải quyết' }, { value: 'CLOSED', label: 'Đã đóng' }, { value: 'CANCELLED', label: 'Đã hủy' }]; const priorities = [{ value: 'LOW', label: 'Thấp' }, { value: 'NORMAL', label: 'Bình thường' }, { value: 'HIGH', label: 'Cao' }, { value: 'URGENT', label: 'Khẩn cấp' }];
const categoryColumns = [{ key: 'category_code', label: 'Mã', mono: true }, { key: 'category_name', label: 'Tên danh mục' }, { key: 'description', label: 'Mô tả' }, { key: 'status', label: 'Trạng thái' }]; const categoryFields = [{ key: 'category_code', label: 'Mã', required: true }, { key: 'category_name', label: 'Tên danh mục', required: true }, { key: 'description', label: 'Mô tả', type: 'textarea', full: true, nullable: true }, { key: 'status', label: 'Trạng thái', type: 'select', options: [{ value: 'ACTIVE', label: 'Hoạt động' }, { value: 'INACTIVE', label: 'Ngừng dùng' }] }];
const summaryCards = computed(() => [{ label: 'Tổng ticket', value: summary.total || 0, className: '' }, { label: 'Chờ xử lý', value: summary.pending || 0, className: 'text-amber-600' }, { label: 'Đang xử lý', value: summary.in_progress || 0, className: 'text-blue-600' }, { label: 'Hoàn tất', value: summary.completed || 0, className: 'text-emerald-600' }]);
const statusLabel = (value) => statuses.find((item) => item.value === String(value || '').toUpperCase())?.label || value || '—'; const priorityLabel = (value) => priorities.find((item) => item.value === String(value || '').toUpperCase())?.label || value || '—'; const statusVariant = (value) => ({ RESOLVED: 'success', CLOSED: 'success', IN_PROGRESS: 'warning', CANCELLED: 'secondary' }[String(value).toUpperCase()] || 'default'); const dateTime = (value) => value ? new Date(value).toLocaleString('vi-VN') : '—';
const loadCategories = async () => { const data = await serviceTicketService.categories(); categories.value = Array.isArray(data) ? data : data?.items || []; };
const load = async () => { loading.value = true; try { const result = await serviceTicketService.list({ ...filters, page: pagination.current_page, per_page: 25 }); tickets.value = result.items; Object.assign(pagination, result.pagination); Object.assign(summary, result.summary || {}); } finally { loading.value = false; } };
const resetAndLoad = () => { pagination.current_page = 1; load(); }; const goPage = (delta) => { pagination.current_page += delta; load(); };
const openCreate = () => { Object.assign(form, { category_id: categories.value[0]?.id ? String(categories.value[0].id) : '', title: '', description: '', priority: 'NORMAL' }); formError.value = ''; createModal.value = true; };
const createTicket = async () => { if (!form.category_id || !form.title.trim() || !form.description.trim()) { formError.value = 'Chọn danh mục, nhập tiêu đề và mô tả'; return; } saving.value = true; try { await serviceTicketService.create({ ...form, category_id: Number(form.category_id) }); createModal.value = false; toast.success('Đã gửi ticket'); await load(); } catch (error) { formError.value = error.response?.data?.message || 'Không thể tạo ticket'; } finally { saving.value = false; } };
const openDetail = async (ticket) => { detailModal.value = true; selected.value = await serviceTicketService.show(ticket.id); Object.assign(manageForm, { status: selected.value.status, priority: selected.value.priority, assigned_to: selected.value.assigned_to || '', comment: '' }); comment.value = ''; };
const updateTicket = async () => { saving.value = true; try { selected.value = await serviceTicketService.update(selected.value.id, { ...manageForm }); Object.assign(manageForm, { status: selected.value.status, priority: selected.value.priority, assigned_to: selected.value.assigned_to || '', comment: '' }); await load(); } catch (error) { toast.error(error.response?.data?.message || 'Không thể cập nhật ticket'); } finally { saving.value = false; } };
const addComment = async () => { selected.value = await serviceTicketService.addUpdate(selected.value.id, comment.value); comment.value = ''; };
const canCancel = (ticket) => ['PENDING', 'OPEN'].includes(String(ticket.status).toUpperCase()); const cancelTicket = async (ticket) => { if (!confirm('Hủy ticket này?')) return; try { await serviceTicketService.cancel(ticket.id); await load(); if (selected.value?.id === ticket.id) detailModal.value = false; } catch (error) { toast.error(error.response?.data?.message || 'Không thể hủy ticket'); } };
onMounted(async () => { await Promise.all([loadCategories(), load()]); });
</script>
